// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/taxonomy/v1/taxonomy.proto

package taxonomypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Taxonomy_GetTaxonomyById_FullMethodName = "/taxonomy.v1.Taxonomy/GetTaxonomyById"
)

// TaxonomyClient is the client API for Taxonomy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxonomyClient interface {
	GetTaxonomyById(ctx context.Context, in *GetTaxonomyByIdRequest, opts ...grpc.CallOption) (*GetTaxonomyByIdResponse, error)
}

type taxonomyClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxonomyClient(cc grpc.ClientConnInterface) TaxonomyClient {
	return &taxonomyClient{cc}
}

func (c *taxonomyClient) GetTaxonomyById(ctx context.Context, in *GetTaxonomyByIdRequest, opts ...grpc.CallOption) (*GetTaxonomyByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaxonomyByIdResponse)
	err := c.cc.Invoke(ctx, Taxonomy_GetTaxonomyById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxonomyServer is the server API for Taxonomy service.
// All implementations must embed UnimplementedTaxonomyServer
// for forward compatibility.
type TaxonomyServer interface {
	GetTaxonomyById(context.Context, *GetTaxonomyByIdRequest) (*GetTaxonomyByIdResponse, error)
	mustEmbedUnimplementedTaxonomyServer()
}

// UnimplementedTaxonomyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaxonomyServer struct{}

func (UnimplementedTaxonomyServer) GetTaxonomyById(context.Context, *GetTaxonomyByIdRequest) (*GetTaxonomyByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxonomyById not implemented")
}
func (UnimplementedTaxonomyServer) mustEmbedUnimplementedTaxonomyServer() {}
func (UnimplementedTaxonomyServer) testEmbeddedByValue()                  {}

// UnsafeTaxonomyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxonomyServer will
// result in compilation errors.
type UnsafeTaxonomyServer interface {
	mustEmbedUnimplementedTaxonomyServer()
}

func RegisterTaxonomyServer(s grpc.ServiceRegistrar, srv TaxonomyServer) {
	// If the following call pancis, it indicates UnimplementedTaxonomyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Taxonomy_ServiceDesc, srv)
}

func _Taxonomy_GetTaxonomyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxonomyByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxonomyServer).GetTaxonomyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Taxonomy_GetTaxonomyById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxonomyServer).GetTaxonomyById(ctx, req.(*GetTaxonomyByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Taxonomy_ServiceDesc is the grpc.ServiceDesc for Taxonomy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Taxonomy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taxonomy.v1.Taxonomy",
	HandlerType: (*TaxonomyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaxonomyById",
			Handler:    _Taxonomy_GetTaxonomyById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/taxonomy/v1/taxonomy.proto",
}
